### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ArthurCamara**
Added TERRIER_HEAP_MEM to indexing script. It reserves 2GB for the system.

### CODE REVIEW

**Review by cmacdonald — COMMENTED** [review]
Mostly looks good. I wonder about reserving 2GB is too much? I'm running on my desktop, and the Docker VM has at most 2GB.

Also typo on avaialable

**Comment by ArthurCamara** [comment]
I was taking the Azure image into consideration. But I think we can decrease to 512MB (or even less)? It's probably more than enough.
(Fixed the typo in the last commit... That has a typo on the message)

**Comment by cmacdonald** [comment]
Sure I can live with 512MB. 
On my container:
```
>>> available_memory/(1024**3)
1.9522056579589844
```

BTW: Are you sure that usable_memory is always computed as an int?

**Comment by ArthurCamara** [comment]
Yes, you are right. There should be a `//` instead of `/`.
I will fix those in a minute
Edit: Ok, now I see what you said. In the documentation, it says so. I will add the integer division just in case.

**Comment by ArthurCamara** [comment]
https://psutil.readthedocs.io/en/latest/index.html?highlight=virtual_memory#psutil.virtual_memory 

> 
> Return statistics about system memory usage as a named tuple including the following fields, expressed in bytes. Main metrics:

> **total**: total physical memory.
>

**Pull request merged**
