### PR TITLE
Update for latest jig breaking changes

### PR DESCRIPTION
**Pull request by ryan-clancy**

### CODE REVIEW

**Comment by ryan-clancy** [comment]
@ArthurCamara I made some updates for the latest jig breaking changes, but I get the following error for `trec_eval` at the end of `jig`'s `search`:

```
###
# out/run.robust04.BM25.topics.robust04.301-450.601-700.txt
###

trec_eval.get_results: Malformed line 4
trec_eval: Quit in file 'out/run.robust04.BM25.topics.robust04.301-450.601-700.txt'
```

where the first few lines of the file in question looks like:

```
301 Q0 FBIS3-21777 0 1.5523202524225514 BM25
310 Q0 FBIS3-21777 0 2.1482664325306478 BM25
322 Q0 FBIS3-21777 0 1.5523202524225514 BM25
334 Q0  0 0.48220054907004917 BM25
334 Q0  1 0.45014565734045664 BM25
339 Q0 FBIS3-21777 0 2.1482664325306478 BM25
359 Q0 "," 0 1.4316967485409062 BM25
360 Q0 FBIS3-21777 0 2.1482664325306478 BM25
366 Q0  0 0.48220054907004917 BM25
366 Q0  1 0.45014565734045664 BM25
```

Can you take a look at it as I've never worked with terrier?

**Comment by ArthurCamara** [comment]
Sorry for the delay...

Will take a look at these today.

**Comment by cmacdonald** [comment]
The index seems to have a document without a docno. That suggests a collection.spec issue? Did you index the readme?

**Comment by ArthurCamara** [comment]
It seems like the problem comes from the different versions of the robust dataset we are using. The files I have here are not compressed and departed by folder for each of the collections. These kind of errors should be easy to catch during development, and I obviously did not. I will try to get the same version as @r-clancy and @lintool are using and debug on that one. If either of you could help me getting that collection, it would be of great help.

**Comment by ArthurCamara** [comment]
So, @r-clancy sent me the collection, and I'm seeing the same problem here.

`$ file /Users/acamara/data/disk45/disk4/cr/efiles/cr93e28.z
/Users/acamara/data/disk45/disk4/cr/efiles/cr93e28.z: compress'd data 16 bits
`

@cmacdonald  That's the output from file'ing one of these. 

If I use gunzip on it, it's actually the expected file:

```
$ gunzip cr93e28.z
$ head cr93e28
<DOC>
<DOCNO> CR93E-6068 </DOCNO>
<DOCID>E18MY3-144</DOCID>
<CENTER><PRE>[Page: E1273]</PRE></CENTER>
<DATE>19930518</DATE>
<FLD003>E</FLD003>
<TEXT>

<TTL>DRUG REVIEW BOARD REWARDS PHARMACEUTICAL RESEARCH AND DEVELOPMENT -- HON. FORTNEY PETE STARK (Extension of Remarks - May 18, 1993)</TTL>
<CENTER>HON. FORTNEY PETE STARK</CENTER>

```

So, they are actually .gz files.

**Comment by cmacdonald** [comment]
> So, they are actually .gz files.

Nope, I checked this last night. Its more that gunzip supports decompression of "compress"' d files. On the other hand, Java's GZIPInputStream does not.

If you move to Terrier's current Github rather than 5.1 vanilla, I committed some patches that makes support for .z files a few properties:
```
terrier.mvn.coords=org.apache.commons:commons-compress:1.18
files.mappings=Z:org.apache.commons.compress.compressors.z.ZCompressorInputStream:null
```

**Comment by ArthurCamara** [comment]
> Nope, I checked this last night. Its more that gunzip supports decompression of "compress"' d files. On the other hand, Java's GZIPInputStream does not.

Yes, just realised this.

> 
> If you move to Terrier's current Github rather than 5.1 vanilla, I committed some patches that makes support for .z files a few properties:
> 

Will give it a shot.

**Comment by ArthurCamara** [comment]
The current version of Terrier-core does not build correctly (tried both on Mac and Linux). When skipping the tests (`mvn install -DskipTests`), it (obviously) fails when running batch_indexing:

```
(base) arthur@deepir:/ssd/home/arthur/terrier/terrier-core$ ./bin/terrier batchindexing
Setting TERRIER_HOME to /ssd/home/arthur/terrier/terrier-core
Setting JAVA_HOME to /usr
16:07:20.662 [main] ERROR o.terrier.indexing.CollectionFactory - ERROR: First Collection class named org.terrier.indexing.TRECCollection  - cannot be instantiated
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_191]
	at org.terrier.indexing.CollectionFactory.loadCollections(CollectionFactory.java:97) [terrier-project-5.1-jar-with-dependencies.jar:na]
	at org.terrier.indexing.CollectionFactory.loadCollection(CollectionFactory.java:76) [terrier-project-5.1-jar-with-dependencies.jar:na]
	at org.terrier.applications.TRECIndexing.loadCollection(TRECIndexing.java:98) [terrier-project-5.1-jar-with-dependencies.jar:na]
	at org.terrier.applications.TRECIndexing.<init>(TRECIndexing.java:68) [terrier-project-5.1-jar-with-dependencies.jar:na]
	at org.terrier.applications.TRECIndexing.<init>(TRECIndexing.java:56) [terrier-project-5.1-jar-with-dependencies.jar:na]
	at org.terrier.applications.BatchIndexing$Command.run(BatchIndexing.java:109) [terrier-project-5.1-jar-with-dependencies.jar:na]
	at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:155) [terrier-project-5.1-jar-with-dependencies.jar:na]
	at org.terrier.applications.CLITool.main(CLITool.java:316) [terrier-project-5.1-jar-with-dependencies.jar:na]
Caused by: java.lang.ExceptionInInitializerError: null
	at org.terrier.indexing.CollectionFactory.loadCollectionSpecFileList(CollectionFactory.java:164) [terrier-project-5.1-jar-with-dependencies.jar:na]
	at org.terrier.indexing.MultiDocumentFileCollection.<init>(MultiDocumentFileCollection.java:108) ~[terrier-project-5.1-jar-with-dependencies.jar:na]
	at org.terrier.indexing.TRECCollection.<init>(TRECCollection.java:198) ~[terrier-project-5.1-jar-with-dependencies.jar:na]
	... 12 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.terrier.utility.Files.initialise_mappings(Files.java:232) ~[terrier-project-5.1-jar-with-dependencies.jar:na]
	at org.terrier.utility.Files.<clinit>(Files.java:174) ~[terrier-project-5.1-jar-with-dependencies.jar:na]
	... 15 common frames omitted
Exception in thread "main" java.lang.IllegalArgumentException: Collection class named TRECCollection not loaded, aborting
	at org.terrier.applications.TRECIndexing.loadCollection(TRECIndexing.java:101)
	at org.terrier.applications.TRECIndexing.<init>(TRECIndexing.java:68)
	at org.terrier.applications.TRECIndexing.<init>(TRECIndexing.java:56)
	at org.terrier.applications.BatchIndexing$Command.run(BatchIndexing.java:109)
	at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:155)
	at org.terrier.applications.CLITool.main(CLITool.java:316)
```

As discussed with Jimmy, for now, we will stick with manually uncompressing the files and indexing them as-is.

**Comment by cmacdonald** [comment]
Ok, I'll give a look at this later.

**Comment by cmacdonald** [comment]
I have fixed this on Terrier's current github.

Craig

**Comment by ArthurCamara** [comment]
Looks like it's working now, using

`bin/terrier batchindexing -Dterrier.mvn.coords=org.apache.commons:commons-compress:1.18 -Dfiles.mappings=z:org.apache.commons.compress.compressors.z.ZCompressorInputStream:null`

**Pull request closed without merging**
