### PR TITLE
Spark

### PR DESCRIPTION
**Pull request by ArthurCamara**

### CODE REVIEW

**Comment by cmacdonald** [comment]
Travis says "The job exceeded the maximum log length, and has been terminated."

Thoughts @ArthurCamara - am I doing too much in the Dockerfile?

**Comment by ArthurCamara** [comment]
I think we are maybe being too verbose on the logs?

**Comment by cmacdonald** [comment]
ah, good point. Will see if I can make it quieter.

**Comment by ArthurCamara** [comment]
All good now! Can I merge it?

**Pull request merged**
